services:
  app:
    image: getting_started
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos
    restart: always
  
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos

volumes:
  todo-mysql-data: